-- ═══════════════════════════════════════════════════════════════════════════════
-- Photography Portfolio — Supabase Schema
-- Run this once in: Supabase Dashboard → SQL Editor → New Query → Run
-- ═══════════════════════════════════════════════════════════════════════════════

-- ── Tables ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS admin_users (
  id            bigint generated by default as identity primary key,
  email         text unique not null,
  password_hash text not null,
  created_at    timestamptz default now()
);

CREATE TABLE IF NOT EXISTS photos (
  id            bigint generated by default as identity primary key,
  filename      text not null,
  original_name text,
  image_url     text default '',
  title         text default '',
  caption       text default '',
  category      text default 'uncategorized',
  featured      boolean default false,
  sort_order    integer default 0,
  created_at    timestamptz default now()
);

-- Add image_url to existing installations that ran the old schema
ALTER TABLE photos ADD COLUMN IF NOT EXISTS image_url   text default '';

-- Add video support to existing installations
ALTER TABLE photos ADD COLUMN IF NOT EXISTS media_type  text default 'photo';
ALTER TABLE photos ADD COLUMN IF NOT EXISTS video_url   text default '';

CREATE TABLE IF NOT EXISTS settings (
  key   text primary key,
  value text default ''
);

CREATE TABLE IF NOT EXISTS messages (
  id         bigint generated by default as identity primary key,
  name       text not null,
  email      text not null,
  message    text not null,
  is_read    boolean default false,
  created_at timestamptz default now()
);

-- ── Default site settings ─────────────────────────────────────────────────────

INSERT INTO settings (key, value) VALUES
  ('site_name',        'Photography Portfolio'),
  ('hero_tagline',     'Capturing moments that last a lifetime'),
  ('hero_subtitle',    'Professional photographer'),
  ('hero_image',       ''),
  ('about_bio',        E'Welcome to my portfolio.\nI capture moments that tell stories.'),
  ('about_image',      ''),
  ('contact_email',    ''),
  ('contact_phone',    ''),
  ('social_instagram', ''),
  ('social_facebook',  ''),
  ('social_twitter',   '')
ON CONFLICT (key) DO NOTHING;

-- ── Disable RLS (server uses service-role key which bypasses it anyway) ────────

ALTER TABLE admin_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE photos      DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings    DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages    DISABLE ROW LEVEL SECURITY;
